#DEV environment
environment:
  message: This is the property file to the ${spring.application.name} specific to DEV environment

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: { ENV_DB_URL }
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  jackson:
    time-zone: America/Sao_Paulo
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true